#!/usr/bin/env bash
set -e

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

copy_file() {

	local path="$1"
	local target=${path//$ORIGINAL/$TARGET}
	
	$(mkdir -p $(dirname $target))

	if [ -f $path ]; then

		if [ ! -f $target ]; then
    		cp $path $target
		fi

	fi

}

ORIGINAL="$1"
TARGET="$2"

for f in $(find $ORIGINAL); do copy_file "$f"; done

# restore $IFS
IFS=$SAVEIFS